### PR TITLE
Increased area, ran testing to verify 5million-ish sqkm works... slowly

### PR DESCRIPTION
**Pull request by StevenPG**

### CODE REVIEW

**Review by MattPetry — APPROVED** [review]

**Review by kteneyck — APPROVED** [review]
What's slower? Getting responses back from the DSS?

**Comment by StevenPG** [comment]
> What's slower? Getting responses back from the DSS?

Correct, there's just more rows being affected when any operation occurs. This is all from testing on my local.

**Comment by javaxpert** [comment]
Can it be done in parallel with smaller areas being run at the same time and somehow joined in the end?

**Comment by StevenPG** [comment]
> Can it be done in parallel with smaller areas being run at the same time and somehow joined in the end?

@alexonesky 

Potentially, it actually stores each cell. It's not like PostGIS at all. If it's in 1000 cells, it saves 1000 rows with the cell listed.

There might be some optimization we can do in the future, but this should work ok enough for now.

**Review by mikepop36 — APPROVED** [review]

**Review by dorayin1 — APPROVED** [review]

**Pull request merged**
